// 六类信号体系元数据
window.SIG_SYSTEM = {
  "catMeta": {
    "趋势": {"color": "#1c7ed6", "desc": "判断股价大方向，上升趋势中找买点 / 判断下跌趋势是否结束"},
    "动量": {"color": "#7950f2", "desc": "判断股价短期是否过度下跌（超卖），捕捉反弹或反转"},
    "量价": {"color": "#e8590c", "desc": "成交量是价格变化的燃料，量价配合验证信号有效性"},
    "K线形态": {"color": "#e03131", "desc": "单根或几根K线组成的特定形态，短期买卖信号"},
    "图表形态": {"color": "#0ca678", "desc": "多根K线形成的中长期价格形态，判断趋势反转或延续"},
    "辅助": {"color": "#f08c00", "desc": "BOLL/BIAS/EMV/BRAR/VR/PSY等辅助类指标"}
  },
  "signalNames": {
    "t_ma_golden": "MA金叉(5上穿20)",
    "t_above_year": "站上年线",
    "t_bull_arrange": "均线多头排列",
    "t_support20": "回踩MA20支撑",
    "t_macd_golden": "MACD金叉",
    "t_macd_red": "MACD红柱",
    "t_macd_div": "MACD底背离",
    "t_dmi_golden": "DMI金叉",
    "t_trix_golden": "TRIX金叉",
    "m_rsi_oversold": "RSI超卖(<30)",
    "m_rsi_golden": "RSI金叉(6穿12)",
    "m_rsi_div": "RSI底背离",
    "m_kdj_golden": "KDJ金叉",
    "m_kdj_low_golden": "KDJ低位金叉",
    "m_kdj_j_neg": "J值<0",
    "m_cci_break": "CCI上穿+100",
    "m_cci_oversold_break": "CCI上穿-100",
    "m_roc_neg": "ROC<0",
    "m_wr_rebound": "W%R超卖反转",
    "v_vol_price_up": "量增价升",
    "v_bottom_volume": "底部放量",
    "v_shrink_pullback": "缩量回调",
    "v_vol_flat": "量增价平",
    "v_obv_div": "OBV底背离",
    "k_hammer": "锤子线",
    "k_inv_hammer": "倒锤子线",
    "k_big_yang": "大阳线",
    "k_engulf": "看涨吞没",
    "k_pierce": "曙光初现",
    "k_three_soldiers": "多方炮",
    "k_rising_three": "上升三法",
    "p_double_bottom": "双底突破",
    "p_breakout": "平台突破",
    "p_support60": "回踩MA60回升",
    "a_boll_rebound": "BOLL下轨反弹",
    "a_bias_neg": "BIAS负偏离",
    "a_emv_pos": "EMV≥0",
    "a_brar_low": "BRAR低位",
    "a_vr_low": "VR<40",
    "a_psy_low": "PSY低位"
  }
};
